#docker build -t web -f services/main/presentation/web/Dockerfile.web services/main/ && docker run --network host -it -t web

FROM ubuntu:20.04

RUN mkdir /app

WORKDIR /app

ENV TZ=Europe/Amsterdam
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y python3.8 python3.8-dev python3-pip htop git

#RUN git clone https://github.com/DanMcInerney/pymetasploit3.git && cd pymetasploit3 && python3 -m pip install .
ADD exploration/agent/resources/pymetasploit3 /tmp/pymetasploit3

RUN cd /tmp/pymetasploit3 && python3 -m pip install .

ADD presentation/web/resources/requirements.txt /app
RUN pip3 install --no-cache-dir -r requirements.txt

COPY lib/Common/Utils/                             /app/lib/Common/Utils/
COPY lib/Common/Exploration/Environment/State.py   /app/lib/Common/Exploration/Environment/State.py
COPY lib/Common/Exploration/Environment/Session.py /app/lib/Common/Exploration/Environment/Session.py
COPY lib/Presentation/Web/                         /app/lib/Presentation/Web/
RUN touch lib/__init__.py && touch lib/Presentation/__init__.py

ADD presentation/web/scripts/web.py /app
ADD presentation/web/resources      /app/resources

CMD python3 /app/web.py
