apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVWGxpRUJuaTcxSFdzTHMyd0xOWE1ldi9BK1d3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXpNRFV3TmpFek5Ea3dPRm9YRFRNegpNRFV3TXpFek5Ea3dPRm93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5OFpvZHZ6L0ZkcHR3TDlZRHhzNFAzYWJrSmwvZ1NRQVJsdHcKcklRUEdBTEw5YXhsWEJwT2puMkRBN3RPOEVsdXI5ZjJYNU1weFRmeWZkSy9LOUtnK1I2WmRUQ09oMDl6Q3dtLwo2c3h1cnI1aDBaU2NZK0M4SjUrd2x1RDg0RTdQR2VsVTA1OEUvbDVWZGE3UWZhclB6OUE2ay9PV0hrdHN6elpsCmM2OXd6cnU3b1Y5TldEVXl0UGtRTG84U0pqU2JLQ1NHZFFPZmFySFo3RHo1a0c5TTZKMDFpM3NHcjgwYnpWWTgKelRMUnJRaDhPUktGWDh3Q1Rkd1M1c01qOHAyelNSODYwcUl3dms0MyszanJpR0JQbXdJN0loZFl1SUwvekJGSAptYUVNS0Y0M09JQ1RTUFowc3dpdXVWVXRWM2d1WlpQajcycmt6SE5OK3JicVhOcmV3UUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVWhBNnlsbzlnQ2JCelBDR29tLzBybHFmdkdSRXdId1lEVlIwakJCZ3dGb0FVaEE2eWxvOWcKQ2JCelBDR29tLzBybHFmdkdSRXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBUmhjNXEyWndQRjFjWTMxSTBsUHFyZEZ0WmpkTXNvY3JGYWgyMTZ5aGtYcE1Vc3psNDNpWE8yMnFFSVlhCmp1ekhrSjNNWXVjWVhyTVVZSS9ZbkRVbFptRU04SkpxVS8vY2RCYnMycFNWa1lhejh5ZEpNQllNbFVTNmZHWlEKOHgyeGN5ekpqQmE2c0kwaW1DZGQyQ3NaMDF3d2ZqbTJDaUdSMjBTeUt5MFRBQ1NNb3pNNGZYQldtaGY5c1RyUwpDd0FEaWpJRzRDUC81NUs1YU0yaVJJZndqd1hxT3VWUTFvSXZQbXJsb3E1MC9iMUw5NEx3bFdxVVVSRDlIZE03CnlvVmFoQnVjd29TVW0vTmdBNEMzelZJMko0b1k5L21zUXhUdVR6bVlVdFJndzVURWF6aFlzTTUwclRvdFFscnIKUVRKSmpRRFVMR3QwQzZZemVuZlo0cWZLRnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://195.201.8.233:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: QXZCc1NoZFBReGg4eFpXNVNsS1daVnlReTNuRmJoRnlzNGZRa0JCbGdEND0K
